// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdYk4ku-6QoaB3SaxkKRBODeNTCWvFTyU',
    appId: '1:917940971160:web:876152329f2b459c2b12ed',
    messagingSenderId: '917940971160',
    projectId: 'blog-app-flutter-ee795',
    authDomain: 'blog-app-flutter-ee795.firebaseapp.com',
    storageBucket: 'blog-app-flutter-ee795.appspot.com',
    measurementId: 'G-PEY4R6D75W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEedCYglH50V0pDddgrcQDCf9oouhD4pk',
    appId: '1:917940971160:android:d98c5496a47e3eaa2b12ed',
    messagingSenderId: '917940971160',
    projectId: 'blog-app-flutter-ee795',
    storageBucket: 'blog-app-flutter-ee795.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyxHqpVHrlwHZaTbw5LLOp5wBuX50GpM',
    appId: '1:917940971160:ios:f617a26a66a96fc92b12ed',
    messagingSenderId: '917940971160',
    projectId: 'blog-app-flutter-ee795',
    storageBucket: 'blog-app-flutter-ee795.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyxHqpVHrlwHZaTbw5LLOp5wBuX50GpM',
    appId: '1:917940971160:ios:f617a26a66a96fc92b12ed',
    messagingSenderId: '917940971160',
    projectId: 'blog-app-flutter-ee795',
    storageBucket: 'blog-app-flutter-ee795.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdYk4ku-6QoaB3SaxkKRBODeNTCWvFTyU',
    appId: '1:917940971160:web:f68cd46b85affb9f2b12ed',
    messagingSenderId: '917940971160',
    projectId: 'blog-app-flutter-ee795',
    authDomain: 'blog-app-flutter-ee795.firebaseapp.com',
    storageBucket: 'blog-app-flutter-ee795.appspot.com',
    measurementId: 'G-QVR49N5YR6',
  );
}
